export const equipmentsData = [
  {
    id: 1,
    src: '/images/equipments/crane-1.jpeg',
    title: 'Crane',
    alt: 'Crane',
    genre: 'cranes',
  },
  {
    id: 2,
    src: '/images/equipments/crane-2.jpeg',
    title: 'Crane',
    alt: 'Crane',
    genre: 'cranes',
  },
  {
    id: 3,
    src: '/images/equipments/crane-3.jpeg',
    title: 'Crane',
    alt: 'Crane',
    genre: 'cranes',
  },
  {
    id: 4,
    src: '/images/equipments/crane-4.jpeg',
    title: 'Crane',
    alt: 'Crane',
    genre: 'cranes',
  },
  {
    id: 5,
    src: '/images/equipments/crane-5.jpeg',
    title: 'Crane',
    alt: 'Crane',
    genre: 'cranes',
  },
  {
    id: 6,
    src: '/images/equipments/forklift-1.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    genre: 'forklifts',
  },
  {
    id: 7,
    src: '/images/equipments/forklift-3.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    genre: 'forklifts',
  },
  {
    id: 71,
    src: '/images/equipments/forklift-4.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    genre: 'forklifts',
  },
  {
    id: 72,
    src: '/images/equipments/forklift-5.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    genre: 'forklifts',
  },
  {
    id: 73,
    src: '/images/equipments/forklift-2.jpeg',
    title: 'Forklift',
    alt: 'forklift',
    genre: 'forklifts',
  },
  {
    id: 8,
    src: '/images/equipments/jcb-backhoe.jpeg',
    title: 'JCB Backhoe',
    alt: 'jcb-backhoe',
    genre: 'jsb-backhoes',
  },
  {
    id: 9,
    src: '/images/equipments/manlift-1.jpeg',
    title: 'Manlift',
    alt: 'manlift',
    genre: 'manlifts',
  },
  {
    id: 10,
    src: '/images/equipments/manlift-2.jpeg',
    title: 'Scissor Lift',
    alt: 'scissor-lift',
    genre: 'scissor-lift',
  },
  {
    id: 11,
    src: '/images/equipments/telehanlder-1.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 12,
    src: '/images/equipments/telehanlder-2.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 13,
    src: '/images/equipments/telehanlder-3.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 14,
    src: '/images/equipments/telehanlder-4.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 15,
    src: '/images/equipments/telehanlder-5.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 16,
    src: '/images/equipments/telehanlder-6.jpeg',
    title: 'Telehanlder',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 17,
    src: '/images/equipments/telehanlder-7.jpeg',
    title: 'Telehanlder and Forklift',
    alt: 'telehanlder',
    genre: 'telehanlders',
  },
  {
    id: 18,
    src: '/images/equipments/towerlight-1.jpeg',
    title: 'Tower Light',
    alt: 'telehanlder',
    genre: 'towerLights',
  },
  {
    id: 19,
    src: '/images/equipments/towerlight-2.jpeg',
    title: 'Tower Light',
    alt: 'telehanlder',
    genre: 'towerLights',
  },
  {
    id: 20,
    src: '/images/equipments/bobcat1.jpeg',
    title: 'Bobcat',
    alt: 'bobcat',
    genre: 'bobcats',
  },
  {
    id: 21,
    src: '/images/equipments/bobcat2.jpeg',
    title: 'Bobcat',
    alt: 'bobcat',
    genre: 'bobcats',
  },
  {
    id: 22,
    src: '/images/equipments/bobcat3.jpeg',
    title: 'Bobcat',
    alt: 'bobcat',
    genre: 'bobcats',
  },
  {
    id: 23,
    src: '/images/equipments/logistics.jpeg',
    title: 'Logistics',
    alt: 'logistics',
    genre: 'logistics',
  },
  {
    id: 24,
    src: '/images/equipments/man-lift.jpeg',
    title: 'Man-lift',
    alt: 'Man-lift',
    genre: 'Manlifts',
  },
  {
    id: 25,
    src: '/images/equipments/man-lift1.jpg',
    title: 'Manlift',
    alt: 'Manlift',
    genre: 'Manlifts',
  },
  {
    id: 26,
    src: '/images/equipments/man-lift-and-scissor-lift.jpg',
    title: 'Manlift & Scissorlift',
    alt: 'Manlift & Scissorlift',
    genre: 'scissor-lift',
  },
  {
    id: 27,
    src: '/images/equipments/scissor-lift.jpg',
    title: 'Scissorlift',
    alt: 'Scissorlift',
    genre: 'scissor-lift',
  },
]
